-- SQL 1: Student table creation and query exercises

CREATE TABLE IF NOT EXISTS STUDENT (
    ROLL_NO TEXT PRIMARY KEY,
    NAME TEXT NOT NULL,
    ADDRESS TEXT,
    PHONE TEXT,
    AGE INTEGER
);

INSERT INTO STUDENT (ROLL_NO, NAME, ADDRESS, PHONE, AGE) VALUES
('1', 'RAM', 'DELHI', 'xxxxxx', 18),
('2', 'RAMESH', 'GURGAON', 'xxxxxx', 18),
('3', 'SUJIT', 'ROHTAK', 'xxxxxx', 20),
('4', 'SURESH', 'DELHI', 'xxxxxx', 18),
('5', 'AMIN', 'ROHTAK', 'xxxxxx', 20),
('6', 'HARSH', 'GURGAON', 'xxxxxx', 18);

-- Sample queries
SELECT * FROM STUDENT;

SELECT * FROM STUDENT WHERE AGE = 18 AND ADDRESS = 'DELHI';
SELECT * FROM STUDENT WHERE AGE = 18 AND NAME = 'RAM';
SELECT * FROM STUDENT WHERE NAME = 'RAM' OR NAME = 'SUJIT';
SELECT * FROM STUDENT WHERE NAME = 'RAM' OR AGE = 20;
SELECT * FROM STUDENT WHERE AGE = 18 AND (NAME = 'RAM' OR NAME = 'RAMESH');

-- End of student queries